// Start Codex outside Chrome's inherited file quarantine on macOS.
// The socket relay follows the Claude host's launchd path. It uses its own
// shim, token and job labels so the two hosts cannot replace each other's state.
import { spawn, execFile } from "node:child_process";
import { EventEmitter } from "node:events";
import { PassThrough } from "node:stream";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync, renameSync, unlinkSync } from "node:fs";
import { join } from "node:path";
import net from "node:net";

const SHIM_SOURCE = `#!/usr/bin/env node
// Generated by codex-spawn.mjs — do not edit. argv: <port> <tokenFile> <spawnId>
import net from "node:net";
import { spawn } from "node:child_process";
import { readFileSync } from "node:fs";

const port = Number(process.argv[2]);
// The shared secret is read from a 0600 file, NOT passed on argv — argv is
// visible in \`ps\` to other local users, and it authenticates receipt of the
// child's full env (secrets included).
const tokenFile = process.argv[3];
const spawnId = process.argv[4];
let token = "";
try { token = readFileSync(tokenFile, "utf8").trim(); } catch { process.exit(0); }

// launchctl submit restarts jobs that exit nonzero — always leave with 0.
const bail = () => process.exit(0);
process.on("uncaughtException", bail);
// Startup watchdog only — cleared once the child is running.
const watchdog = setTimeout(bail, 15000);

function connect(chan, cb) {
  const sock = net.connect({ port: port, host: "127.0.0.1" }, () => {
    sock.setNoDelay(true);
    sock.write(JSON.stringify({ token: token, spawnId: spawnId, chan: chan }) + "\\n", () => cb(sock));
  });
  sock.on("error", bail);
  return sock;
}

connect("ctl", (ctl) => {
  connect("io", (io) => {
    ctl.setEncoding("utf8");
    let buf = "";
    const onData = (chunk) => {
      buf += chunk;
      const nl = buf.indexOf("\\n");
      if (nl < 0) return;
      ctl.off("data", onData);
      let spec;
      try {
        spec = JSON.parse(buf.slice(0, nl));
      } catch {
        return bail();
      }
      run(ctl, io, spec);
    };
    ctl.on("data", onData);
  });
});

function run(ctl, io, spec) {
  clearTimeout(watchdog);
  const say = (obj) => {
    try {
      ctl.write(JSON.stringify(obj) + "\\n");
    } catch {}
  };
  let child;
  try {
    child = spawn(spec.cmd, spec.args, { cwd: spec.cwd, env: spec.env, stdio: ["pipe", "pipe", "pipe"] });
  } catch (err) {
    say({ type: "error", message: String(err && err.message) });
    return setTimeout(bail, 100);
  }
  child.on("spawn", () => say({ type: "spawned", pid: child.pid }));
  child.on("error", (err) => {
    say({ type: "error", message: String(err && err.message) });
    setTimeout(bail, 100);
  });
  child.stdin.on("error", () => {});
  io.pipe(child.stdin);
  child.stdout.pipe(io);
  child.stderr.on("data", (c) => say({ type: "stderr", data: c.toString("utf8") }));
  child.on("close", (code, signal) => {
    say({ type: "exit", code: code, signal: signal });
    setTimeout(bail, 150); // let the ctl write flush
  });
  // Host gone — don't leave an orphaned Codex running headless.
  ctl.on("close", () => {
    try {
      child.kill("SIGKILL");
    } catch {}
    setTimeout(bail, 50);
  });
}
`;

export function createCodexSpawner({ hostDir, nodePath = process.execPath, redact = () => {} }) {
  if (process.platform !== "darwin") {
    return { spawn: (cmd, args, opts) => spawn(cmd, args, { ...opts, stdio: ["pipe", "pipe", "pipe"] }), close() {} };
  }
  const instanceId = randomBytes(8).toString("hex");
  const SHIM_PATH = join(hostDir, "codex-spawn-shim.mjs");
  const SPAWN_TOKEN_FILE = join(hostDir, ".codex-spawn-token-" + instanceId);
  const SPAWN_TOKEN = randomBytes(32).toString("hex");
  redact(SPAWN_TOKEN);
  const pendingSpawns = new Map();
  const sockets = new Set();
  let nextSpawnId = 1, spawnPort = 0, closed = false, server;
  const spawnReady = new Promise((resolve, reject) => {
    try {
      if (!existsSync(SHIM_PATH) || readFileSync(SHIM_PATH, "utf8") !== SHIM_SOURCE) {
        const tmp = SHIM_PATH + "." + instanceId + ".tmp";
        writeFileSync(tmp, SHIM_SOURCE, "utf8");
        renameSync(tmp, SHIM_PATH);
      }
      writeFileSync(SPAWN_TOKEN_FILE, SPAWN_TOKEN, { mode: 0o600, flag: "wx" });
      server = net.createServer((sock) => {
        sockets.add(sock);
        sock.on("close", () => sockets.delete(sock));
        sock.on("error", () => {});
        sock.setTimeout(10000, () => sock.destroy());
        let buf = Buffer.alloc(0);
        const onData = (chunk) => {
          buf = Buffer.concat([buf, chunk]);
          const nl = buf.indexOf(10);
          if (nl < 0) { if (buf.length > 4096) sock.destroy(); return; }
          sock.off("data", onData);
          let hello;
          try { hello = JSON.parse(buf.subarray(0, nl).toString("utf8")); } catch {}
          const child = hello?.token === SPAWN_TOKEN && pendingSpawns.get(hello.spawnId);
          if (!child) { sock.destroy(); return; }
          sock.setTimeout(0);
          child._attach(hello.chan, sock, buf.subarray(nl + 1));
        };
        sock.on("data", onData);
      });
      server.on("error", reject);
      server.listen(0, "127.0.0.1", () => {
        if (closed) { server.close(); resolve(); return; }
        spawnPort = server.address().port; resolve();
      });
    } catch (err) { reject(err); }
  });
  // A setup error reaches the caller when it asks to start Codex.
  spawnReady.catch(() => {});

  function lineJsonReader(onMsg) {
    let buf = "";
    return (chunk) => {
      buf += chunk;
      let nl;
      while ((nl = buf.indexOf("\n")) >= 0) {
        const line = buf.slice(0, nl); buf = buf.slice(nl + 1);
        let msg;
        try { msg = JSON.parse(line); } catch { continue; }
        onMsg(msg);
      }
    };
  }
  class DetachedCodex extends EventEmitter {
    constructor(cmd, args, opts) {
      super();
      this.pid = null;
      this.exitCode = null;
      this.signalCode = null;
      this.killed = false;
      this.stdin = new PassThrough(); // buffers writes until the io channel is up
      this.stdout = new PassThrough();
      this.stderr = new PassThrough();
      this.stdin.on("error", () => {});
      this._spec = { cmd, args, cwd: opts.cwd, env: opts.env };
      this._spawnId = String(nextSpawnId++);
      this._label = "com.lizard.codex." + process.pid + "." + instanceId + "." + this._spawnId;
      this._ctl = null;
      this._io = null;
      this._pendingSig = null;
      this._ioEnded = false;
      this._exitResult = null;
      this._done = false;
      pendingSpawns.set(this._spawnId, this);
      this._startupTimer = setTimeout(() => this._fail(new Error("Timed out starting ChatGPT through launchd. Reopen the Studio panel and try again.")), 10000);
      spawnReady.then(() => {
        if (this._done) return;
        execFile(
          "/bin/launchctl",
          ["submit", "-l", this._label, "--", nodePath, SHIM_PATH, String(spawnPort), SPAWN_TOKEN_FILE, this._spawnId],
          { timeout: 10000 },
          (err) => { if (err) this._fail(new Error("Could not start ChatGPT through launchd: " + err.message)); }
        );
      }, (err) => this._fail(err));
    }

    _attach(chan, sock, rest) {
      if (this._done) {
        sock.destroy();
        return;
      }
      if (chan === "ctl" && !this._ctl) {
        this._ctl = sock;
        sock.setEncoding("utf8");
        const feed = lineJsonReader((m) => this._ctlMsg(m));
        if (rest && rest.length) feed(rest.toString("utf8"));
        sock.on("data", feed);
        sock.on("close", () => {
          // ctl gone without an exit message: the shim (or its job) died on us.
          if (!this._done && !this._exitResult) this._fail(new Error("ChatGPT launch relay closed unexpectedly."));
        });
      } else if (chan === "io" && !this._io) {
        this._io = sock;
        if (rest && rest.length) this.stdout.write(rest);
        sock.on("data", (c) => { if (!this.stdout.write(c)) sock.pause(); });
        this.stdout.on("drain", () => sock.resume());
        sock.on("end", () => {
          this._ioEnded = true;
          this.stdout.end();
          if (this._exitResult) this._finish(...this._exitResult);
        });
        sock.on("error", (err) => this._fail(err));
        this.stdin.pipe(sock);
      } else {
        sock.destroy();
        return;
      }
      if (this._ctl && this._io) {
        // Send the command only after both channels connect.
        try {
          this._ctl.write(JSON.stringify(this._spec) + "\n");
        } catch {}
      }
    }

    _ctlMsg(m) {
      if (this._done) return;
      if (m.type === "spawned") {
        clearTimeout(this._startupTimer);
        this.pid = m.pid || null;
        if (this._pendingSig && this.pid) {
          try {
            process.kill(this.pid, this._pendingSig);
          } catch {}
          this._pendingSig = null;
        }
        this.emit("spawn");
      } else if (m.type === "stderr") {
        this.stderr.write(m.data || "");
      } else if (m.type === "exit") {
        this._exitResult = [m.code == null ? null : m.code, m.signal || null];
        if (this._ioEnded) this._finish(...this._exitResult);
      } else if (m.type === "error") {
        this._fail(new Error(m.message || "spawn failed"));
      }
    }

    _finish(code, signal) {
      if (this._done) return;
      this._done = true;
      this.exitCode = code;
      this.signalCode = signal;
      this._cleanup();
      this.stdout.end();
      this.stderr.end();
      this.emit("exit", code, signal);
    }

    _fail(err) {
      if (this._done) return;
      this._done = true;
      this.exitCode = 1;
      this._cleanup();
      this.stdout.end();
      this.stderr.end();
      this.emit("error", err);
      this.emit("exit", 1, null);
    }

    _cleanup() {
      clearTimeout(this._startupTimer);
      pendingSpawns.delete(this._spawnId);
      execFile("/bin/launchctl", ["remove", this._label], () => {});
      // Give the io socket a beat to drain Codex's last stdout bytes, then close
      // both channels (which also tells a still-alive shim to clean itself up).
      const socks = [this._ctl, this._io];
      const t = setTimeout(() => {
        for (const s of socks) {
          try {
            s && s.destroy();
          } catch {}
        }
      }, 250);
      t.unref?.();
    }

    kill(sig = "SIGTERM") {
      if (this._done) return false;
      this.killed = true;
      if (this.pid) {
        try {
          process.kill(this.pid, sig);
        } catch {}
        return true;
      }
      this._pendingSig = sig; // no pid yet — deliver as soon as the shim reports it
      return true;
    }
  }


  return {
    spawn(cmd, args, opts) {
      if (closed) throw new Error("ChatGPT launcher is closed.");
      return new DetachedCodex(cmd, args, opts);
    },
    close() {
      if (closed) return;
      closed = true;
      for (const child of [...pendingSpawns.values()]) {
        child.kill("SIGTERM");
        child._finish(null, "SIGTERM");
      }
      for (const sock of sockets) sock.destroy();
      server?.close();
      try { unlinkSync(SPAWN_TOKEN_FILE); } catch {}
    },
  };
}
