"use strict";

window.runEditPanelTests = async function () {
  const t = window.__test, checks = [];
  const check = (name, ok) => { if (!ok) throw new Error(name); checks.push(name); };
  const pause = () => new Promise((resolve) => setTimeout(resolve, 0));
  const emit = (msg) => t.emit({ id: "edit-a", ...msg });
  const event = (data) => emit({ type: "event", data });
  const result = () => event({ type: "result", subtype: "success", usage: {} });
  const user = (n) => ({ type: "user", historyTurnId: "turn-" + n, historyItemId: "user-" + n,
    message: { content: [{ type: "text", text: "Question " + n }] } });
  const answer = (n) => ({ type: "assistant", historyTurnId: "turn-" + n, historyItemId: "answer-" + n,
    message: { id: "answer-" + n, content: [{ type: "text", text: "Answer " + n }], usage: {} } });
  const history = (request, events, nextCursor) => emit({ type: "transcript", paged: true, done: true,
    sessionId: request.sessionId, requestId: request.requestId, events, nextCursor });
  t.emit({ type: "ready", ok: true, version: 33, home: "/test", user: "Test" });
  t.emit({ type: "agentReady", agent: "codex", ok: true, version: 8 });
  emit({ type: "started", cwd: "/test/project", permissionMode: "workspace" });
  event({ type: "system", subtype: "init", agent: "codex", session_id: "thread-edit", model: "test-model", cwd: "/test/project" });
  history(t.posted("loadTranscript").at(-1), [user(2), answer(2), user(3), answer(3)], { kind: "turns", value: "before-2" });
  const box = document.querySelector(".chat-messages:not(.hidden)");
  const first = () => box.querySelector(".sent-edit");
  check("loaded user messages have edit buttons", box.querySelectorAll(".sent-edit").length === 2);
  first().click();
  let input = box.querySelector(".msg-edit");
  check("editing opens the original text", input.value === "Question 2");
  input.value = "Cancelled";
  box.querySelector(".msg-edit-cancel").click();
  check("Cancel keeps the original history and sends nothing", !box.querySelector(".msg-edit") && box.textContent.includes("Question 2") && !t.posted("rewind").length);
  first().click(); input = box.querySelector(".msg-edit");
  input.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", shiftKey: true, bubbles: true }));
  input.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", isComposing: true, bubbles: true }));
  check("Shift+Enter and IME confirmation do not send", !t.posted("rewind").length);
  input.value = "Changed question";
  box.querySelector(".msg-edit-save").click();
  const failed = t.posted("rewind").at(-1);
  check("edit uses the stored turn ID and live chat ID", failed.id === "edit-a" && failed.turnId === "turn-2" && failed.itemId === "user-2" && failed.agent === "codex");
  check("history stays visible until the host confirms", box.textContent.includes("Answer 3") && input.disabled);
  emit({ type: "rewindResult", requestId: "stale", ok: true });
  check("unrelated acknowledgements cannot cut history", box.textContent.includes("Answer 3"));
  emit({ type: "rewindResult", requestId: failed.requestId, ok: false, running: false, error: "Test rollback failure" });
  check("failed edits keep the draft and later replies", !input.disabled && input.value === "Changed question" && box.textContent.includes("Answer 3"));
  box.querySelector(".msg-edit-save").click();
  const saved = t.posted("rewind").at(-1);
  box.querySelector(".msg-edit-save").click();
  check("double clicks send a single request", t.posted("rewind").length === 2);
  emit({ type: "rewindResult", requestId: saved.requestId, ok: true, previousTurnId: "turn-1" });
  check("confirmed edits replace the selected message and later replies", box.textContent.includes("Changed question") && !box.textContent.includes("Answer 3") && !box.textContent.includes("Question 2"));
  emit({ type: "promptAccepted", messageId: saved.requestId, turnId: "replacement" });
  check("the replacement can be edited again", box.querySelectorAll(".sent-edit").length === 1);
  event({ type: "assistant", message: { id: "replacement-reply", content: [{ type: "text", text: "New answer" }], usage: {} } }); result();
  box.querySelector(".history-more").click();
  check("editing the first loaded turn keeps older history reachable", t.posted("loadTranscript").at(-1).cursor.through === "turn-1");
  history(t.posted("loadTranscript").at(-1), [user(1), answer(1)], null);
  first().click(); input = box.querySelector(".msg-edit"); input.value = "Earlier edit";
  input.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", bubbles: true }));
  const older = t.posted("rewind").at(-1);
  check("an older page edits the real chat rather than its temporary renderer", older.id === "edit-a" && older.turnId === "turn-1");
  emit({ type: "rewindResult", requestId: older.requestId, ok: false, running: false, error: "Keep for test" });
  input.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape", bubbles: true }));
  const composer = document.querySelector("#composer-input");
  composer.value = "Live question"; composer.dispatchEvent(new Event("input", { bubbles: true }));
  composer.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", bubbles: true })); await pause();
  const prompt = t.posted("prompt").at(-1);
  check("new prompts have a correlation ID", !!prompt.messageId && prompt.text.includes("Live question"));
  emit({ type: "promptAccepted", messageId: prompt.messageId, turnId: "live-turn" });
  const liveRow = [...box.querySelectorAll(".msg-user")].find((row) => row.textContent.includes("Live question"));
  liveRow.querySelector(".sent-edit").click();
  liveRow.querySelector(".msg-edit").value = "Live correction";
  liveRow.querySelector(".msg-edit-save").click();
  const liveEdit = t.posted("rewind").at(-1);
  check("running messages can restart their own turn", liveEdit.turnId === "live-turn");
  composer.value = "Queued after edit"; composer.dispatchEvent(new Event("input", { bubbles: true }));
  composer.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", bubbles: true })); await pause();
  check("prompts submitted during an edit wait in the queue", t.posted("prompt").length === 1);
  emit({ type: "rewindResult", requestId: liveEdit.requestId, ok: true });
  emit({ type: "promptAccepted", messageId: liveEdit.requestId, turnId: "live-replacement" });
  result(); await pause();
  check("queued prompts resume once after the replacement finishes", t.posted("prompt").length === 2 && t.posted("prompt").at(-1).text.includes("Queued after edit"));
  result();
  check("the panel reports no runtime errors", t.errors.length === 0);
  first().click();
  input = box.querySelector(".msg-edit"); input.value = "Keep this edit after disconnect";
  box.querySelector(".msg-edit-save").click();
  t.disconnect();
  check("disconnect unlocks the editor and preserves its text", !input.disabled && input.value === "Keep this edit after disconnect" && box.textContent.includes("Answer 1"));
  check("disconnect causes no browser errors", t.errors.length === 0);
  return { passed: checks.length, checks };
};
